### ISSUE TITLE
Add Exposures API to Translator Registry

### ISSUE THREAD

**Issue by stevencox** [ResearchSoftwareInstitute/greendatatranslator#100]
Annotate with ENVO ontology.

**Comment by lstillwe** [comment]
In order to create JSON_LD, need to find vocab definitions for the CMAQ variables listed below.
So far I have been able to find those marked with an "x".
I need some help understanding what the acronyms mean in order to find more.
Also I was unable to find some - for example "relative humidity" (I think that is what "RH" means)
Wondering id I should create a separate issue for Sarav to track these down or just use this issue for all?

ALD2 
ALDX
x BENZENE
x CO
x ETH
ETHA
FORM
x H2O2
x HNO3
HNO3_UGM3
x HONO
CLNO2
HOX
x OH
IOLE
ISOP
x N2O5
x NH3
NH3_UGM3
NHX
x NO
x NO2
ANO3_PPB
NTR
PANS
NOY
O3 - Ozone
OLE
PAR
x PAN
PANX
x SO2
SO2_UGM3
x SULF
TERP
TOL
x VOC
x XYL
XYLMN
AFEJ
AALJ
ASIJ
ATIJ
ACAJ
AMGJ
AKJ
AMNJ
ASOILJ
AHPLUSIJ
ANAK
AMGK
AKK
ACAK
ACLIJ
AECIJ
ANAIJ
ANO3IJ
ANO3K
TNO3
ANH4IJ
ANH4K
AOCIJ
AOMIJ
AORGAJ
AORGBJ
AORGCJ
APOCIJ
APOAIJ
ASO4IJ
ASO4K
ATOTI
ATOTJ
ATOTK
PMIJ
PM10
AUNSPEC1IJ
ANCOMIJ
AUNSPEC2IJ
AOMOCRAT_PRI
AOMOCRAT_TOT
PM25_HP
PM25_CL
PM25_EC
PM25_NA
PM25_MG
PM25_K
PM25_CA
PM25_NH4
PM25_NO3
PM25_OC
PM25_SOIL
PM25_SO4
PM25_TOT
PM25_UNSPEC1
PM25RD
PMC_CL
PMC_NA
PMC_NH4
PMC_NO3
PMC_SO4
PMC_TOT
DCV_Recon
x AIR_DENS - air density??
RH - relative humidity?? Cannot find definition
SFC_TMP
PBLH
x SOL_RAD - solar radiation??
precip - precipitation
WSPD10
WDIR10
K
P1
P2
P3
a
K_prime
sqrt_Ki
max_NO3_loss
PM25_NO3_loss
ANO3IJ_loss
PM25_NH4_loss
ANH4IJ_loss
PMIJ_FRM
PM25_FRM

**Comment by arunacs** [comment]
[CMAQ_Species_Defn_CheBI_Links.xlsx](https://github.com/ResearchSoftwareInstitute/greendatatranslator/files/1848040/CMAQ_Species_Defn_CheBI_Links.xlsx)

Lisa, here is the complete list, with expanded chemical names plus links to the CheBI database that was discussed.  Note that your list is a bit different from mine. I went with identifying only those that are common in the 2 years of data, per prior discussion with Mike.

**Comment by arunacs** [comment]
Here is an updated file (See new tab Union.2010-2011 added) to match the species listed above on this ticket, which is a Union of the model species from the 2010 and 2011 CMAQ model outputs provided.
[CMAQ_Species_Defn_CheBI_Links.Rev1.xlsx](https://github.com/ResearchSoftwareInstitute/greendatatranslator/files/1853768/CMAQ_Species_Defn_CheBI_Links.Rev1.xlsx)

**Comment by lstillwe** [comment]
Running behind with this hope to have something by 4/9 - 75% done.
