### ISSUE TITLE
CMAQ Exposures Data - expanded temporal and geospatial reach

### ISSUE THREAD

**Issue by lstillwe** [ResearchSoftwareInstitute/greendatatranslator#123]
Exposures cmaq API has already been expanded to include the entire US for years 2010 & 2011.
This issue can also include additional quality metrics to be provided by @arunacs and installed by @lstillwe.

**Comment by lstillwe** [comment]
@arunacs  provided new quality metrics here:

DQ metrics in similar format to previously provided sample for O3 are now available for both years for several gas-phase and aerosol pollutants.
/proj/ie/proj/NIH-DataTranslator/for_RENCI/CMAQ/2010/Evaluation/*.csv
and
/proj/ie/proj/NIH-DataTranslator/for_RENCI/CMAQ/2011/Evaluation*.csv

@mjstealey warned that we are already at max column width for postgresql table for quality metrics - may need a redesign.

**Comment by karafecho** [comment]
Current CMAQ data needs:

Sarav to provide expanded ontology/chemical names for union of two years of data. Variables common to both years can be found here: CMAQ_Species_Defn_CheBI_Links.xlsx.
Sarav to explore why data points are missing for at least several days in two-year dataset.

**Comment by karafecho** [comment]
**Hao's 'cleaned' CMAQ output:**

***File location:**

/opt/RENCI/output/

The 2010 data is under the cmaq2010 directory
The 2011 data is under the cmaq2011 directory

**Hourly files:**

C<col>R<row>.csv

Header: start_date, ozone, pm2.5

**Daily files:**

C<col>R<row>Daily.csv

Header: start_time, o3_avg, pm25_avg, o3_max, pm25_max, o3_min, pm25_min, o3_stddev, pm25_stddev

**Comment by karafecho** [comment]
A few somewhat randomly selected articles that may be of interest to some of you: [Reference #1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4486042/); [Reference #2](https://www.ncbi.nlm.nih.gov/pubmed/27385358).

**Caveat:** The exposure estimates in these articles are lower than the US EPA AQI breakpoints. This is because the AQI breakpoints provide benchmarks for all persons (children plus adults, healthy and non-healthy), are skewed toward extreme weather events, and are not as granular as we propose for pediatric patients with asthma, who are more sensitive than adults to airborne pollutants. US EPA AQI breakpoints: 24-h average: 0-12, 12.1-35.4, 35.5-55.4, 55.5-150.4, 150.5-250.4, 250.5-350.4, 350.5-500.4 μg/m3. US EPA overall guidelines are maximum PM2.5: 12.0 μg/m3 over 1 year, 35 μg/m3 over 24 hours.

**Caveat:** We're not as much interested in a case-control study between patients with asthma-like conditions and patients without asthma-like conditions (or "healthy", whatever that means), but rather we're trying to delineate subpopulations of patients with asthma-like conditions. Short-term (24 hours/one week/two weeks) and long-term (e.g., average annual) exposures are equally informative, but they address somewhat different questions.

**Comment by karafecho** [comment]
@arunacs , @lstillwe : We failed to discuss the following issue earlier today.

Sarav to provide expanded ontology/chemical names for union of two years of data. Variables common to both years can be found here: CMAQ_Species_Defn_CheBI_Links.xlsx.

**Comment by arunacs** [comment]
@karafecho See issue #100 where I provided an updated file, and looks like @lstillwe has taken care of it

**Comment by karafecho** [comment]
As per discussion on 4/11/18, plans are as follows:

1. Temporal expansion of existing Exposures Service/API - Explore whether we can obtain additional years of data on CMAQ exposures (beyond 2010, 2011) from the US EPA [Sarav]
2. Spatial expansion of existing Exposures Service/API - Generate higher-resolution CMAQ estimates - one year likely by end of feasibility assessment [Sarav's student]
3. Pollutant expansion of existing Exposures Service/API - Incorporate additional exposure estimates for 2010 and 2011 (not just PM2.5, ozone) [Lisa]
4. Data quality metrics for Exposures Service/API - Stick with current metrics for PM2.5 and ozone (2010, 2011), at least for the time being [Lisa]
5. R-LINE - hold off on this effort, at least for now [Sarav]
