### ISSUE TITLE
Definition of HuSH+

### ISSUE THREAD

**Issue by rayi113** [ResearchSoftwareInstitute/greendatatranslator#30]
- 90 % complete

**Comment by karafecho** [comment]
This is complete but needs approval from NCATS.

**Comment by karafecho** [comment]
We define ‘real-world’ and 'HuSH+’ (HIPAA Safe Harbor Plus) patient data as follows. Real-world patient data sets are comprised of real observational patient data; as such, the data can be used for clinical interpretation, scientific inference, and discovery. In contrast, HuSH+ patient data sets are completely compliant with §164.514(b) of HIPAA, 'Safe Harbor' method for patient de-identification of medical records (https://www.hhs.gov/hipaa/for-professionals/privacy/special-topics/de-identification/). In addition, HuSH+ patient data sets have had all real patient identifiers replaced with random patient identifiers and dates shifted by a random number of days such that the resultant data set is comprised of hypothetical patients with fictional drug exposures and health outcomes, but the data are representative of the types of relationships expected to be observed within real observational patient data sets. Because the HuSH+ data are only representative of hypothetical patients, drug exposures, and health outcomes, the data cannot be used for clinical interpretation, nor scientific inference nor discovery.

**Comment by karafecho** [comment]
Definition sent to Orange Team for vetting.
