### ISSUE TITLE
Create Artificial PM 2.5 Data

### ISSUE THREAD

**Issue by rayi113** [ResearchSoftwareInstitute/greendatatranslator#8]
- 100 percent complete

**Comment by arunacs** [comment]
* 90% complete

Submitted sample data to Lisa on 2/22.
Tweaked the sample a little bit now, and will send revised sample.

**Comment by arunacs** [comment]
[sample_cmaq_output_updated.zip](https://github.com/ResearchSoftwareInstitute/greendatatranslator/files/848104/sample_cmaq_output_updated.zip)

**Comment by mjstealey** [comment]
@arunacs, @ahannaIE - Couple questions regarding this data.
@lstillwe as fyi.

As it stands, it's 3 days worth of PM25 data for 3 locations (Raleigh, Durham, Chapel Hill)

```
ID,Lat,Lon,Col,Row,Date,O3_ppb,PM25_Primary_ugm3,PM25_Secondary_ugm3
Raleigh,35.7795897,-78.6381787,122,50,2010-01-01 00:00:00,4.67542219161987,10.2763252258301,10.2763252258301
Raleigh,35.7795897,-78.6381787,122,50,2010-01-01 01:00:00,10.6597690582275,8.6428804397583,8.6428804397583
Raleigh,35.7795897,-78.6381787,122,50,2010-01-01 02:00:00,11.7991485595703,8.97025680541992,8.97025680541992
Raleigh,35.7795897,-78.6381787,122,50,2010-01-01 03:00:00,15.6943092346191,8.31261157989502,8.31261157989502
...
```

Questions:
1. Is **PM25_Primary_ugm3** always supposed to be equal to **PM25_Secondary_ugm3**? Because it is in this sample.
2. What is the timezone for the **Date** attribute? (local, UTC, GMT...)
3. Would it be possible to get a 21-28 day range of data? This would assist in formulating the 7-day and 14-day risk calculations for risk score. Or we could just re-spam 3 days over and over again.

I may be missing something... @lstillwe feel free to add.

**Comment by arunacs** [comment]
Responses:
1. In this dummy data, they are equal, since we are still developing an approach. Expect real data to be different for the 2 fields.
2. TZ is UTC
3. Sure, will send along longer time period

**Comment by lstillwe** [comment]
Also wondered what the row and column fields represent?

**Comment by arunacs** [comment]
They refer to the Col, Row index in the modeling domain, each at 36x36 km resolution. For your purposes, I think can be ignored. We like to track that for internal QA on our end.
However, this will also be useful later on to understand why some lat/lons will have the same concentration estimates, since they happen to be in the same grid-cell, and hence have the same Col, Row index.

**Comment by mjstealey** [comment]
> In this dummy data, they are equal, since we are still developing an approach. Expect real data to be different for the 2 fields.

For testing purposes we may want to perturb the value for PM25_Secondary_ugm3. Is there a general relationship between the primary and the secondary? or could we just delta it by some value between 0 and 1? 

For return values the specs we're working with seem to want a sum of primary and secondary. For return scores this is not only additive, but then looked at across a 7 or 14 day period. Perturbing these would make things feel a bit more real for testing on our side.

On 2. and 3. 👍

**Comment by arunacs** [comment]
It will vary, and hence our work to develop a robust approach. For now, you may go with one of following options for testing purposes:
a) Take either of the current values and assign 10% to Primary and 90% to Secondary 
b) Retain Secondary as such, and assign 10% to Primary.

**Comment by arunacs** [comment]
[sample_cmaq_36km_output_long.zip](https://github.com/ResearchSoftwareInstitute/greendatatranslator/files/863440/sample_cmaq_36km_output_long.zip)

Attached is a month-long sample dataset
